/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.xlido;
import java.util.*;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.ArrayList;
import java.util.HashSet;

public class App {
    int userIdCounter = 1;
    List<String> userEmails = new LinkedList<>();
    
    int eventIdCounter = 1;
    List<String> events = new LinkedList<>();
    List<Integer> eventCreators = new LinkedList<>();
    
    List<String> questions = new LinkedList<>();
    List<Integer> questionEventIds = new LinkedList<>();
    List<Integer> questionUserIds = new LinkedList<>();
    List<Integer> questionCreators = new LinkedList<>();
    
    List<Set<Integer>> questionUpvotes = new ArrayList<>();
    List<List<String>> questionReplies = new ArrayList<>();
    
    List<Integer> questionIds = new ArrayList<>();

    public static void main(String[] args) {
        

        if (args.length == 1){
            List<String> commandLineArgs = new LinkedList<>(Arrays.asList(args));
            String inputFile = commandLineArgs.get(0).split("=")[1];
            try {
                List<String> file_commands = Files.readAllLines(Paths.get(inputFile));
                // Execute the commands
                new App().run(file_commands);
            } catch (IOException e) {
                e.printStackTrace();
            }
            return;
        }        

        List<String> inplace_commands = new LinkedList<>(){
            {
            }
        };

        new App().run(inplace_commands);
 
    }
    public boolean run(List<String> commands){
        boolean isSuccessful = true;

        Iterator<String> it = commands.iterator();
        while(it.hasNext()){
            String line = it.next();
                if(line == null){
                    break;
                }
                List<String> tokens = Arrays.asList(line.split(","));

                try {
                   
                    switch(tokens.get(0)){
                        // TODO: Validate email/password format if required by problem statement
// TODO: If user already exists, print correct error and do not increment counter
                        case "CREATE_USER":
                        
    String email = tokens.get(1);
    String password = tokens.get(2);

   
    if (userEmails.contains(email)) {
        System.out.println("ERROR: USER_ALREADY_EXISTS");
        isSuccessful = false;
        break;
    }

    // create user
    userEmails.add(email);
    int currentUserId = userIdCounter;
    userIdCounter++;

    System.out.println("User ID: " + currentUserId);

                        break;

                        // TODO: Check userId exists (1 <= userId <= userEmails.size())
// TODO: Store event and organizer correctly
// TODO: Increment event counter only after successful creation
                        case "CREATE_EVENT":{
                       
    String eventName = tokens.get(1);
    int userId = Integer.parseInt(tokens.get(2));

    
    if (userId > userEmails.size()) {
        System.out.println("ERROR: User with an id " + userId + " does not exist");
        isSuccessful = false;
        break;
    }

   
    events.add(eventName);
    eventCreators.add(userId);
    int currentEventId = eventIdCounter;
    eventIdCounter++;

    System.out.println("Event ID: " + currentEventId);
  

                        break;
} 
// TODO: Check user exists
// TODO: Check event exists AND events.get(eventId-1) != null
// TODO: Check if the deleting user is organizer of the event
// TODO: Mark event as deleted (set null)
// TODO: IMPORTANT: Deleting event should affect related questions (either ignore them later or delete them logically)
                        case "DELETE_EVENT":{
    int eventId = Integer.parseInt(tokens.get(1));
    int userId = Integer.parseInt(tokens.get(2));

   
    if (userId < 1 || userId > userEmails.size()) {
        System.out.println("ERROR: User with an id " + userId + " does not exist");
        break;
    }

   
    if (eventId < 1 || eventId > events.size() || events.get(eventId - 1) == null) {
        System.out.println("ERROR: Event with an id " + eventId + " does not exist");
        break;
    }

    
    int creatorId = eventCreators.get(eventId - 1);
    if (creatorId != userId) {
        System.out.println(
            "ERROR: User with an id " + userId +
            " is not a organizer of Event with an id " + eventId
        );
        break;
    }

   
    events.set(eventId - 1, null);
    eventCreators.set(eventId - 1, null);

    System.out.println("EVENT_DELETED " + eventId);
    break;
                    }

                    // TODO: Check user exists
// TODO: Check event exists AND events.get(eventId-1) != null (deleted event should not allow adding question)
// TODO: Add question content, store eventId and creator
// TODO: Initialize upvotes and replies list for this question
    case "ADD_QUESTION": {

        String content = tokens.get(1);
        int userId = Integer.parseInt(tokens.get(2));
        int eventId = Integer.parseInt(tokens.get(3));
    
     
        if (userId < 1 || userId > userEmails.size()) {
            System.out.println("ERROR: User with an id " + userId + " does not exist");
            break;
        }
        
     
        if (eventId < 1 || eventId > events.size()|| events.get(eventId - 1) == null) {
            System.out.println("ERROR: Event with an id " + eventId + " does not exist");
            break;
        }
        
        questions.add(content);
        questionUserIds.add(userId);
        questionEventIds.add(eventId);
        questionCreators.add(userId);
        questionUpvotes.add(new HashSet<>());
        questionReplies.add(new ArrayList<>());

        int questionId = questionIds.size()+1;
        questionIds.add(questionId);
        System.out.println("Question ID: " + questionId);
    
        break;
    }
    // TODO: Check user exists
// TODO: Check question exists AND questions.get(questionId-1) != null
// TODO: Check if user is author of the question
// TODO: Mark question as deleted (set null)
// TODO: Replies/upvotes should remain but LIST_QUESTIONS must ignore deleted question
                       
    case "DELETE_QUESTION": {
        int questionId = Integer.parseInt(tokens.get(1));
        int userId = Integer.parseInt(tokens.get(2));
    
        if (userId < 1 || userId > userEmails.size()) {
            System.out.println("ERROR: User with an id " + userId + " does not exist");
            break;
        }
    
        if (questionId < 1 || questionId > questions.size()
            || questions.get(questionId - 1) == null) {
            System.out.println("ERROR: Question with an id " + questionId + " does not exist");
            break;
        }
    
        int creatorId = questionCreators.get(questionId - 1);
        if (creatorId != userId) {
            System.out.println(
                "ERROR: User with an id " + userId +
                " is not an author of question with an id " + questionId
            );
            break;
        }
    
        questions.set(questionId - 1, null);
        questionCreators.set(questionId - 1, null);
    
        System.out.println("QUESTION_DELETED " + questionId);
        break;
    }
    
    // TODO: Check user exists
// TODO: Check question exists AND questions.get(questionId-1) != null
// TODO: Prevent same user from upvoting same question twice
// TODO: Add userId to upvote set
    case "UPVOTE_QUESTION": {
        int questionId = Integer.parseInt(tokens.get(1));
        int userId = Integer.parseInt(tokens.get(2));
    
        // Step 1: user exists
        if (userId < 1 || userId > userEmails.size()) {
            System.out.println("ERROR: User with an id " + userId + " does not exist");
            break;
        }
    
        
        if (questionId < 1 || questionId > questions.size()
                || questions.get(questionId - 1) == null) {
            System.out.println("ERROR: Question with an id " + questionId + " does not exist");
            break;
        }
    
      
        Set<Integer> upvotes = questionUpvotes.get(questionId - 1);
        if (upvotes.contains(userId)) {
            System.out.println(
                "ERROR: User with an id " + userId +
                " has already upvoted a question with an id " + questionId
            );
            break;
        }
    
        
        upvotes.add(userId);
        System.out.println("QUESTION_UPVOTED " + questionId);
        break;
    }

    // TODO: Check user exists
// TODO: Check question exists AND questions.get(questionId-1) != null
// TODO: Store reply in correct format (User <id>: <content>)
// TODO: Do not allow reply on deleted question
    case "REPLY_QUESTION": {
        String replyContent = tokens.get(1);
        int questionId = Integer.parseInt(tokens.get(2));
        int userId = Integer.parseInt(tokens.get(3));
    

        if (userId < 1 || userId > userEmails.size()) {
            System.out.println("ERROR: User with an id " + userId + " does not exist");
            break;
        }
    
        
        if (questionId < 1 || questionId > questions.size()
                || questions.get(questionId - 1) == null) {
            System.out.println("ERROR: Question with an id " + questionId + " does not exist");
            break;
        }
    
      
        questionReplies.get(questionId - 1)
    .add("User " + userId + ": " + replyContent);

        System.out.println("REPLY_ADDED");
        break;
    }
 // TODO: Check event exists AND events.get(eventId-1) != null
// TODO: Collect only questions that belong to this event AND are not deleted
// TODO: If POPULAR: sort by votes desc, tie by questionId asc
// TODO: If RECENT: sort by questionId desc
// TODO: Print output EXACTLY as expected (spacing/newlines matter)
// TODO: If no questions exist for event, print nothing
    
    case "LIST_QUESTIONS": {
        int eventId = Integer.parseInt(tokens.get(1));
        String sortBy = tokens.get(2);
    
        
        if (eventId < 1 || eventId > events.size() || events.get(eventId - 1) == null) {
            System.out.println("ERROR: Event with an id " + eventId + " does not exist");
            isSuccessful = false;
            break;
        }
    
        List<Integer> list = new ArrayList<>();
    
       
        for (int i = 0; i < questions.size(); i++) {
            if (questions.get(i) != null
        && questionEventIds.get(i) != null
        && questionEventIds.get(i) == eventId) {

                list.add(i);
            }
        }
    
        if (sortBy.equals("POPULAR")) {
            list.sort((a, b) -> {
                int v1 = questionUpvotes.get(a).size();
                int v2 = questionUpvotes.get(b).size();
                if (v1 != v2) return v2 - v1;
                return a - b;
            });
        } else {
            list.sort((a, b) -> b - a);
        }
    
        if (list.isEmpty()) {
            break;
        }
        
        for (int i : list) {
            System.out.println("Question ID: " + (i + 1));
            System.out.println("Content: " + questions.get(i));
            System.out.println("Votes: " + questionUpvotes.get(i).size());
            System.out.println("Replies:");
            for (String r : questionReplies.get(i)) {
                System.out.println("  - " + r);
            }
            System.out.println();
        
        }
        break;
    }
    
                     default:
                           break;
                }
                } catch (Exception e) {
                    System.out.println("ERROR: " + e.getMessage());
                    isSuccessful = false;
                }
        }
        return isSuccessful;

    }
}
